openapi: 3.0.1
info:
  title: BPD HB Payment Instruments API
  description: ''
  version: v2
servers:
  - url: https://test.cstar.pagopa.it/bpd/hb/payment-instruments/v2
paths:
  /:
    delete:
      summary: deletePaymentInstrumentHB
      operationId: deletepaymentinstrumenthb
      parameters:
        - name: id
          in: header
          description: 'id dello strumento di pagamento, che corrisponde al PAN (Primary Account Number) cifrato pgp del metodo di pagamento'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: ''
    get:
      summary: statusPaymentInstrumentHB
      operationId: statuspaymentinstrumenthb
      parameters:
        - name: id
          in: header
          description: 'id dello strumento di pagamento, che corrisponde al PAN (Primary Account Number) cifrato pgp del metodo di pagamento'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInstrumentResource'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: ''
    patch:
      summary: patchPaymentInstrument
      operationId: patchPaymentInstrument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchPaymentInstrumentDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentPaymentInstrumentResource'
        '404':
          description: ''
        '401':
          description: ''
        '500':
          description: ''
  /bpay:
    delete:
      summary: BPay deletePaymentInstrumentHB
      operationId: 5fdb377a52411ce8e7b9d5f6
      parameters:
        - name: id
          in: query
          description: id dello strumento che corrisponde a ABI+Numero cifrati
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: ''
    get:
      summary: BPay statusPaymentInstrumentHB
      operationId: 5fdb37ee7e211f8e0ac2dc45
      parameters:
        - name: id
          in: query
          description: id dello strumento che corrisponde a ABI+Numero cifrato
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInstrumentResource'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: ''
components:
  schemas:
    EnrollmentPaymentInstrumentResource:
      title: EnrollmentPaymentInstrumentResource
      type: object
      properties:
        activationDate:
          type: string
          description: Timestamp dell’attivazione dello strumento di pagamento. FORMATO  ISO8601 yyyy-MM-ddTHH:mm:ss.SSSXXXXX
          format: date-time
    PaymentInstrumentResource:
      title: PaymentInstrumentResource
      type: object
      properties:
        activationDate:
          type: string
          format: date-time
        deactivationDate:
          type: string
          format: date-time
        fiscalCode:
          type: string
        hpan:
          type: string
        Status:
          enum:
            - ACTIVE
            - INACTIVE
          type: string
    PatchPaymentInstrumentDto:
      title: PatchPaymentInstrumentDto
      type: object
      properties:
        id:
          type: string
          description: 'id dello strumento di pagamento, che corrisponde al PAN (Personal Account Number) cifrato pgp'
        fiscalCode:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
        tokenPanList:
          type: array
          items:
            type: string
          description: elenco dei PAN tokenizzati collegati alla scheda fisica
        PAR:
          type: string
          description: corrisponde al Payment Account Reference
    PaymentInstrumentDto:
      title: PaymentInstrumentDto
      type: object
      properties:
        id:
          type: string
          description: 'id dello strumento di pagamento, che corrisponde al PAN (Personal Account Number) cifrato pgp'
        fiscalCode:
          type: string
          description: 'id dell''utente, che corrisponde al codice fiscale'
        expireYear:
          type: integer
          description: anno di scadenza dello strumento di pagamento
        expireMonth:
          type: string
          description: mese di scadenza dello strumento di pagamento
        issuerAbiCode:
          type: string
          description: codice ABI della banca emittente carta
        brand:
          enum:
            - VISA
            - MASTERCARD
            - MAESTRO
            - VISA_ELECTRON
            - AMEX
            - OTHER
            - PAGOBANCOMAT
          type: string
          description: 'tipo circuito (es. Visa, Mastercard)'
        holder:
          type: string
          description: titolare carta (nome e cognome)
        type:
          enum:
            - PP
            - DEB
            - CRD
          type: string
          description: 'tipologia carta (es. PP, DEB, CRD)'
        channel:
          type: string
          description: canale che identifica univocamente l'issuer sulla piattaforma
        tokenPanList:
          type: array
          items:
            type: string
          description: elenco dei PAN tokenizzati collegati alla scheda fisica
        PAR:
          type: string
          description: corrisponde al Payment Account Reference
      example:
        id: string
        fiscalCode: string
        expireYear: 0
        expireMonth: string
        issuerAbiCode: string
        brand: string
        holder: string
        type: string
        channel: string
        tokenPanList:
          - string
        PAR: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]